version: "3.1"

services:
  osrm-backend:
    image: tetzschner/osrm-backend:latest
    ports:
      - 127.0.0.1:5000:15000
    volumes:
      - osrm-data:/osrm-data
    networks:
      - frontend
    deploy:
      replicas: 2
    environment:
      REPLICA_NUMBER: "{{.Task.Slot}}"
      OSRM_PBF_URL: 'https://download.geofabrik.de/europe/denmark-latest.osm.pbf'
      OSRM_UPDATE_DATA_TAG: '2024-04-14 20:20'

networks:
  frontend:


volumes:
  osrm-data:
