version: "3.1"

services:
  osrm-backend:
    image: tetzschner/osrm-backend:latest
    ports:
      - 127.0.0.1:5000:15000
    volumes:
      - osrm-data:/osrm-data
    environment:
      OSRM_PBF_URL: 'https://download.geofabrik.de/europe/andorra-latest.osm.pbf'
      OSRM_UPDATE_DATA_TAG: '1'

#volumes:
  osrm-data:
